source 'https://rubygems.org'

gem 'bcrypt-ruby', '~> 3.0.0'
gem 'cancan'
gem 'devise'
gem 'jquery-rails'
gem 'rails', '3.2.12'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'zurb-foundation'
end
